from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1026, 712)
        Form.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fr_window = QtWidgets.QFrame(parent=Form)
        self.fr_window.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_window.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_window.setObjectName("fr_window")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fr_window)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fr_title = QtWidgets.QFrame(parent=self.fr_window)
        self.fr_title.setMaximumSize(QtCore.QSize(16777215, 40))
        self.fr_title.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_title.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_title.setObjectName("fr_title")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fr_title)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_title = QtWidgets.QLabel(parent=self.fr_title)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_title.setFont(font)
        self.lb_title.setObjectName("lb_title")
        self.verticalLayout.addWidget(self.lb_title, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_4.addWidget(self.fr_title)
        self.sc_list = QtWidgets.QScrollArea(parent=self.fr_window)
        self.sc_list.setWidgetResizable(True)
        self.sc_list.setObjectName("sc_list")
        self.sc_contents = QtWidgets.QWidget()
        self.sc_contents.setGeometry(QtCore.QRect(0, 0, 986, 570))
        self.sc_contents.setObjectName("sc_contents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sc_contents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fr_list = QtWidgets.QFrame(parent=self.sc_contents)
        self.fr_list.setMaximumSize(QtCore.QSize(16777215, 260))
        self.fr_list.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_list.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_list.setObjectName("fr_list")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fr_list)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.fr_product = QtWidgets.QFrame(parent=self.fr_list)
        self.fr_product.setMinimumSize(QtCore.QSize(750, 240))
        self.fr_product.setMaximumSize(QtCore.QSize(16777215, 250))
        self.fr_product.setStyleSheet("background-color: rgb(207, 255, 227);\n"
"border-radius:20%")
        self.fr_product.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_product.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_product.setObjectName("fr_product")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fr_product)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fr_pic = QtWidgets.QFrame(parent=self.fr_product)
        self.fr_pic.setMaximumSize(QtCore.QSize(220, 220))
        self.fr_pic.setStyleSheet("background-color: rgb(134, 255, 168);")
        self.fr_pic.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_pic.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_pic.setObjectName("fr_pic")
        self.lb_pic = QtWidgets.QLabel(parent=self.fr_pic)
        self.lb_pic.setGeometry(QtCore.QRect(10, 10, 200, 200))
        self.lb_pic.setMinimumSize(QtCore.QSize(200, 200))
        self.lb_pic.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_pic.setFont(font)
        self.lb_pic.setText("")
        self.lb_pic.setPixmap(QtGui.QPixmap("../vm/products/kitkat.jpg"))
        self.lb_pic.setScaledContents(True)
        self.lb_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_pic.setObjectName("lb_pic")
        self.horizontalLayout_2.addWidget(self.fr_pic)
        self.fr_price = QtWidgets.QFrame(parent=self.fr_product)
        self.fr_price.setMinimumSize(QtCore.QSize(250, 210))
        self.fr_price.setMaximumSize(QtCore.QSize(250, 210))
        self.fr_price.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_price.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_price.setObjectName("fr_price")
        self.lb_name = QtWidgets.QLabel(parent=self.fr_price)
        self.lb_name.setGeometry(QtCore.QRect(50, 40, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_name.setFont(font)
        self.lb_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_name.setObjectName("lb_name")
        self.lb_price = QtWidgets.QLabel(parent=self.fr_price)
        self.lb_price.setGeometry(QtCore.QRect(50, 120, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_price.setFont(font)
        self.lb_price.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_price.setObjectName("lb_price")
        self.horizontalLayout_2.addWidget(self.fr_price)
        self.fr_amt = QtWidgets.QFrame(parent=self.fr_product)
        self.fr_amt.setMaximumSize(QtCore.QSize(220, 250))
        self.fr_amt.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_amt.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_amt.setObjectName("fr_amt")
        self.btn_high = QtWidgets.QPushButton(parent=self.fr_amt)
        self.btn_high.setGeometry(QtCore.QRect(140, 60, 31, 35))
        self.btn_high.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.btn_high.setFont(font)
        self.btn_high.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.btn_high.setIconSize(QtCore.QSize(16, 16))
        self.btn_high.setObjectName("btn_high")
        self.btnlow = QtWidgets.QPushButton(parent=self.fr_amt)
        self.btnlow.setGeometry(QtCore.QRect(60, 60, 31, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnlow.sizePolicy().hasHeightForWidth())
        self.btnlow.setSizePolicy(sizePolicy)
        self.btnlow.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.btnlow.setFont(font)
        self.btnlow.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.btnlow.setIconSize(QtCore.QSize(16, 14))
        self.btnlow.setObjectName("btnlow")
        self.lb_quan = QtWidgets.QLabel(parent=self.fr_amt)
        self.lb_quan.setGeometry(QtCore.QRect(90, 60, 51, 35))
        self.lb_quan.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lb_quan.setFont(font)
        self.lb_quan.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_quan.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_quan.setObjectName("lb_quan")
        self.lb_amt = QtWidgets.QLabel(parent=self.fr_amt)
        self.lb_amt.setGeometry(QtCore.QRect(40, 120, 150, 61))
        self.lb_amt.setMinimumSize(QtCore.QSize(150, 0))
        self.lb_amt.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_amt.setFont(font)
        self.lb_amt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_amt.setObjectName("lb_amt")
        self.horizontalLayout_2.addWidget(self.fr_amt)
        self.horizontalLayout_4.addWidget(self.fr_product)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.fr_list, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.sc_list.setWidget(self.sc_contents)
        self.verticalLayout_4.addWidget(self.sc_list)
        self.fr_footer = QtWidgets.QFrame(parent=self.fr_window)
        self.fr_footer.setMinimumSize(QtCore.QSize(0, 40))
        self.fr_footer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_footer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_footer.setObjectName("fr_footer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fr_footer)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_back = QtWidgets.QPushButton(parent=self.fr_footer)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_back.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius:10%")
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_3.addWidget(self.btn_back)
        self.lb_tot_amt = QtWidgets.QLabel(parent=self.fr_footer)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb_tot_amt.setFont(font)
        self.lb_tot_amt.setObjectName("lb_tot_amt")
        self.horizontalLayout_3.addWidget(self.lb_tot_amt, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.fr_footer)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(71, 255, 117);\n"
"border-radius:10%")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_4.addWidget(self.fr_footer, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_3.addWidget(self.fr_window)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb_title.setText(_translate("Form", "View Order"))
        self.lb_name.setText(_translate("Form", "Kitkat"))
        self.lb_price.setText(_translate("Form", "Rs. 20"))
        self.btn_high.setText(_translate("Form", "+"))
        self.btnlow.setText(_translate("Form", "-"))
        self.lb_quan.setText(_translate("Form", "0"))
        self.lb_amt.setText(_translate("Form", "Amt : Rs. 0"))
        self.btn_back.setText(_translate("Form", "Back"))
        self.lb_tot_amt.setText(_translate("Form", "Total Amount: Rs. 0"))
        self.pushButton_2.setText(_translate("Form", "Grab Order"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
