# Generated by Django 5.0.6 on 2024-07-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=30)),
                ('ph_no', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('place', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='static/pics')),
            ],
        ),
    ]
